import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { parse } from '@pixelagent/parser';
import {
  toReact,
  toHtml,
  toSwiftUI,
  sha256Hex,
  verifySynthesizedCode,
} from '../src/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const loginDsl = readFileSync(
  resolve(here, '../../dsl-spec/examples/login.dsl'),
  'utf8',
);

describe('@pixelagent/codegen', () => {
  it('exports toReact, toHtml, toSwiftUI as functions', () => {
    expect(typeof toReact).toBe('function');
    expect(typeof toHtml).toBe('function');
    expect(typeof toSwiftUI).toBe('function');
  });

  describe('toReact(login.dsl)', () => {
    const { scene, warnings } = parse(loginDsl);
    if (!scene) throw new Error(`login.dsl failed to parse: ${JSON.stringify(warnings)}`);
    const code = toReact(scene);

    it('emits a single default-exported functional component with contract props', () => {
      expect(code).toMatch(
        /export default function \w+\(\{ text = \{\}, on = \{\} \}: GeneratedScreenProps\)/,
      );
      expect(code.match(/export default function/g)?.length).toBe(1);
      expect(code).toContain('return (');
      expect(code).toMatch(/^\/\/ GENERATED by PixelAgent -- dsl-sha256:/);
    });

    it('uses absolute positioning for top-level nodes', () => {
      expect(code).toContain('absolute');
      expect(code).toContain(`w-[1440px]`);
      expect(code).toContain(`h-[900px]`);
    });

    it('includes the resolved primary color token (#185FA5) on the primary button', () => {
      expect(code).toContain('#185FA5');
      expect(code).toMatch(/bg-\[#185FA5\][^"]*">\{text\['login-btn'\] \?\? "Sign in"\}/);
    });

    it('includes the resolved surface color token (#ffffff) on the login card', () => {
      expect(code).toContain('#ffffff');
    });

    it('includes the radius token literal (12) on the login card', () => {
      expect(code).toContain('rounded-[12px]');
      expect(code).toContain('rounded-[6px]');
    });

    it('renders the "Sign in" label as a text prop default and an :hover bg from STATE', () => {
      expect(code).toContain(`{text['login-btn'] ?? "Sign in"}</button>`);
      expect(code).toContain(`onClick={on['login-btn']}`);
      expect(code).toContain('hover:bg-[#0C447C]');
    });

    it('renders the inputs with their labels', () => {
      expect(code).toContain('>Email</label>');
      expect(code).toContain('>Password</label>');
      expect(code).toContain('type="email"');
      expect(code).toContain('type="password"');
    });

    it('produces no source containing the literal "any"-type annotation', () => {
      expect(code).not.toMatch(/:\s*any\b/);
    });
  });

  describe('semantic intent codegen + synthesis contract', () => {
    const dsl = [
      'SCREEN 800 600',
      'STACK top 0 0 direction:row gap:8 role:nav',
      '  TEXT brand 0 0 "PXL"',
      'END',
      'TEXT title 40 100 "Hello" size:32 level:h1',
      'IMAGE hero 40 200 200 100 "https://x/y.png" alt:"Hero shot" href:"https://example.com"',
      'BUTTON cta 40 340 160 44 "Docs" href:"https://docs.example.com"',
      '',
    ].join('\n');
    const { scene, warnings } = parse(dsl);
    if (!scene) throw new Error(`parse failed: ${JSON.stringify(warnings)}`);
    const code = toReact(scene);

    it('level emits a heading tag', () => {
      expect(code).toMatch(
        /<h1 id="title"[^>]*>\{text\['title'\] \?\? "Hello"\}<\/h1>/,
      );
    });

    it('role emits a semantic container tag', () => {
      expect(code).toContain('<nav id="top"');
      expect(code).toContain('</nav>');
    });

    it('IMAGE emits a real img with alt, wrapped in its href anchor', () => {
      expect(code).toMatch(
        /<a href="https:\/\/example\.com"><img id="hero"[^>]*src="https:\/\/x\/y\.png" alt="Hero shot"/,
      );
      expect(code).not.toContain('data-src');
    });

    it('BUTTON href wraps in an anchor', () => {
      expect(code).toMatch(/<a href="https:\/\/docs\.example\.com"><button id="cta"/);
    });

    it('verifySynthesizedCode validates the header hash and detects drift', () => {
      const signed = toReact(scene, { dslSha256: sha256Hex(dsl) });
      expect(verifySynthesizedCode(signed, dsl)).toBe(true);
      expect(verifySynthesizedCode(signed, `${dsl}\n# touched`)).toBe(false);
      expect(
        verifySynthesizedCode(signed.replace('GENERATED', 'EDITED'), dsl),
      ).toBe(false);
    });

    it('is deterministic: same scene + hash → byte-identical output', () => {
      const h = sha256Hex(dsl);
      expect(toReact(scene, { dslSha256: h })).toBe(
        toReact(scene, { dslSha256: h }),
      );
    });
  });

  describe('toReact theme handling', () => {
    it('theme:dark adds canvas classes and ghost uses light text (renderer parity)', () => {
      const dsl = `SCREEN 800 600 theme:dark\nBUTTON g 10 10 120 40 "Ghost" variant:ghost\n`;
      const { scene } = parse(dsl);
      expect(scene).not.toBeNull();
      const code = toReact(scene!);
      expect(code).toContain('bg-[#111827] text-[#E5E7EB]');
      expect(code).toContain('bg-transparent text-[#E5E7EB]');
      expect(code).toContain(`{text['g'] ?? "Ghost"}`);
      expect(code).not.toContain('text-black');
    });

    it('theme:light keeps ghost text black and no dark canvas (regression)', () => {
      const dsl = `SCREEN 800 600\nBUTTON g 10 10 120 40 "Ghost" variant:ghost\n`;
      const { scene } = parse(dsl);
      const code = toReact(scene!);
      expect(code).toContain('bg-transparent text-black');
      expect(code).not.toContain('#111827');
    });
  });
});
