import { createHash } from 'node:crypto';

export const sha256Hex = (s: string): string =>
  createHash('sha256').update(s, 'utf8').digest('hex');

const HEADER_RE =
  /^\/\/ GENERATED by PixelAgent -- dsl-sha256:([0-9a-f]{64}) -- /;

/**
 * Synthesis-contract drift check: true iff `code` carries the generated
 * header and its embedded hash matches `dsl` byte-for-byte. A hand-edited
 * generated file or a DSL changed without regeneration both fail — CI can
 * gate on this instead of trusting that nobody touched the output.
 */
export const verifySynthesizedCode = (code: string, dsl: string): boolean => {
  const m = HEADER_RE.exec(code);
  return m !== null && m[1] === sha256Hex(dsl);
};
